"""Render governance artifacts from their sources of truth.

Two generators, one principle — *governance metadata is derived, never
hand-maintained*:

* **PII tag DDL** is generated from the data contracts' ``pii`` flags
  (``quality/contracts``). If a contract marks a field as PII, the SQL that
  tags every physical vault column carrying that field exists automatically;
  nobody keeps a second list. Because staging renames some columns on their
  way into the vault, the contract-field → physical-column placement map
  lives here in code — and rendering *fails* if a contract PII field has no
  physical placement, which is the drift gate that keeps the map honest.
* **The access matrix** is rendered from ``grants.yaml`` into reviewer-
  friendly markdown — the artifact an auditor actually reads.

Outputs land in ``governance/unity_catalog/generated/`` and are committed:
CI regenerates and fails on diff (the same trick as generated API docs).
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

import yaml

from quality.contracts.loader import load_contracts

GENERATED_DIR = Path(__file__).resolve().parent / "generated"
GRANTS_PATH = Path(__file__).resolve().parent / "grants.yaml"

# Where each contract PII field physically lands in the vault
# (three-part UC names; bronze raw_value is treated as wholly restricted —
# its catalog grant covers it, column tags don't apply to a JSON blob).
# contract field -> [(table, physical column)]
PII_PLACEMENTS: dict[str, list[tuple[str, str]]] = {
    "actor_login": [
        ("silver.raw_vault.hub_actor", "actor_login"),
        ("gold.marts.developer_360_mart", "actor_login"),
    ],
    "actor_display_login": [
        ("silver.raw_vault.sat_actor_profile", "display_login"),
        ("gold.marts.developer_360_mart", "display_login"),
    ],
    "actor_avatar_url": [
        ("silver.raw_vault.sat_actor_profile", "avatar_url"),
        ("gold.marts.developer_360_mart", "avatar_url"),
    ],
    "assignee_login": [
        # assignees become hub_actor rows; their login is already covered by
        # the hub placement. The resolved assignee resurfaces in gold:
        ("gold.marts.collaboration_mart", "active_assignee"),
    ],
}


def render_pii_tag_sql() -> str:
    """Unity Catalog ``SET TAGS`` statements derived from contract PII flags."""
    header = [
        "-- GENERATED by governance/unity_catalog/render.py — do not edit.",
        "-- Source of truth: quality/contracts/definitions/*.yaml (pii flags)",
        "-- plus the PII_PLACEMENTS physical-column map in render.py.",
        "-- Apply with a UC-enabled SQL warehouse or spark.sql loop.",
        "",
    ]
    statements: set[str] = set()
    for name, contract in sorted(load_contracts().items()):
        for field in contract.fields:
            if not field.pii:
                continue
            placements = PII_PLACEMENTS.get(field.name)
            if placements is None:
                raise SystemExit(
                    f"contract {name!r} marks {field.name!r} as PII but "
                    "PII_PLACEMENTS has no physical column for it — update the map"
                )
            statements.update(
                f"ALTER TABLE {table} ALTER COLUMN {column} "
                f"SET TAGS ('pii' = 'true', 'pii_category' = '{field.pii_category}');"
                for table, column in placements
            )
    return "\n".join(header + sorted(statements)) + "\n"


def render_access_matrix() -> str:
    """Markdown access matrix from grants.yaml, for review and audit evidence."""
    raw: dict[str, Any] = yaml.safe_load(GRANTS_PATH.read_text(encoding="utf-8"))
    principals = {p["name"]: p for p in raw["principals"]}
    securables = sorted({g["securable"] for g in raw["grants"]})

    lines = [
        "<!-- GENERATED by governance/unity_catalog/render.py - do not edit. -->",
        "<!-- Source of truth: governance/unity_catalog/grants.yaml -->",
        "",
        "# Unity Catalog Access Matrix",
        "",
        "| Principal | Kind | " + " | ".join(s.split("/", 1)[1] for s in securables) + " |",
        "|---|---|" + "---|" * len(securables),
    ]
    for name, principal in sorted(principals.items()):
        cells = []
        for securable in securables:
            privileges = [
                g["privileges"]
                for g in raw["grants"]
                if g["principal"] == name and g["securable"] == securable
            ]
            if privileges:
                short = ", ".join(
                    p for p in privileges[0] if p not in ("USE_CATALOG", "USE_SCHEMA")
                )
                cells.append(short or "USE")
            else:
                cells.append("—")
        lines.append(f"| {name} | {principal['kind']} | " + " | ".join(cells) + " |")

    lines += [
        "",
        "PII inventory (derived from contracts + physical placement map):",
        "",
        "| Contract field | Category | Physical columns |",
        "|---|---|---|",
    ]
    documented: dict[str, tuple[str, list[str]]] = {}
    for _, contract in sorted(load_contracts().items()):
        for field in contract.pii_fields:
            columns = [f"`{t}.{c}`" for t, c in PII_PLACEMENTS.get(field.name, [])]
            documented[field.name] = (str(field.pii_category), columns)
    for field_name, (category, columns) in sorted(documented.items()):
        lines.append(f"| {field_name} | {category} | {', '.join(columns)} |")
    lines.append("")
    return "\n".join(lines)


def write_generated() -> list[Path]:
    GENERATED_DIR.mkdir(exist_ok=True)
    outputs = {
        GENERATED_DIR / "pii_tags.sql": render_pii_tag_sql(),
        GENERATED_DIR / "access_matrix.md": render_access_matrix(),
    }
    for path, content in outputs.items():
        path.write_text(content, encoding="utf-8")
    return list(outputs)


def main() -> int:
    for path in write_generated():
        print(f"rendered {path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
